### PR TITLE
Separated params for backup and tidy cronjobs - Fixes #3

### LINKED ISSUE #3: backup_keep = 2 actually keeps backups for 3 days
In manifests/config.pp the module creates two cronjobs with the following oneliners:
`command => "/usr/bin/influxd backup -portable ${influxdb::backup_directory}";`
`command => "/usr/bin/find ${influxdb::backup_directory} -mtime +${influxdb::backup_keep} -type f -delete";`

If backup_keep is set to 2, this creates something like:
`/usr/bin/find /var/lib/influxdb/backups -mtime +2 -type f -delete`

Now, both cronjobs are created to run at the exact same time, which results in a race condition: under certain circumstances, the tidying cronjob runs before the backup cronjon does. This results in the backup location running low on disk space, triggering "false alerts". 

The solution is to introduce separate parameters for both cron jobs.

### PR DESCRIPTION
**Pull request by gmwubs**
In manifests/config.pp the module creates a cronjob with the following oneliner:
command => "/usr/bin/find ${influxdb::backup_directory} -mtime +${influxdb::backup_keep} -type f -delete";

If backup_keep is set to 2, this creates something like:
/usr/bin/find /var/lib/influxdb/backups -mtime +2 -type f -delete

This is caused by the cronjobs for backup and tidy being created to run at the exact same time. In certain circumstances, this results in the the backup location running low on disk space, triggering "false alerts".

The solution introduced here separates parameters for both cron jobs, avoiding a race condition between the two cron jobs.

### CODE REVIEW

**Comment by xandm** [comment]
Thanks - can you also update data/common.yaml (lines 11 and 12) to have new default settings?

**Comment by gmwubs** [comment]
Of course! Sorry I didn't think of that!

**Comment by xandm** [comment]
I don't mind merging it in the current state but wonder if the `daily_backup_hour` should be later than `daily_tidy_hour` so tidy happens first?

**Comment by gmwubs** [comment]
At first, I thought it was perhaps best to create a backup first. On second thought: if the space available is not enough, the backup will fail. I would suggest people make sure that they do off-line backups, for example by creating snapshots or syncing the locally created backups elsewhere :-)

**Comment by gmwubs** [comment]
Any indication when this PR will be accepted?

**Pull request merged**
